server_addr: smtp.gmail.com
server_port: 587
sender_addr: datasf.etls@gmail.com
sender_password: M3VqRXN3YVQ=
etl_recipients: janine.heiser@sfgov.org,jason.lally@sfgov.org
bcc:
email_situations:
    email_txt_basedir: /home/ubuntu/metadata-mgmt-tool/configs/email_txt/
    review_steward:
        text_file_main: email_guidance.txt
        text_file_subparts: ["email_field_cnt_finished.txt", "email_field_cnt_unfinished.txt"]
        subject_line: "[datasf] Please Verify and Fill in Missing Documentation for the Datasets You Manage"
        string_order: steward_name, number_of_fields_to_document, datasets_to_review, worksheet_filename
