#dir configs
config_dir: /Users/j9/Desktop/metadata-mgmt-tool/configs/
pickle_dir: /Users/j9/Desktop/metadata-mgmt-tool/pickled/
pickle_data_dir: /Users/j9/Desktop/metadata-mgmt-tool/pickled/datasets/
wkbk_output_dir: /Users/j9/Desktop/metadata-mgmt-tool/output_wkbks/
log_dir: /Users/j9/Desktop/metadata-mgmt-tool/logs/
wkbk_uploads_dir: /Users/j9/Desktop/metadata-mgmt-tool/wkbk_uploads/


#other yaml configs
socrata_client_config_fname: socrata_config.yaml
metadataset_config: metadatasets.yaml
email_config_file: email_config.yaml
#email_config_fname: email_config.yaml


#file names
wkbk_output_json: workbooks_info.json
exception_logfile: generate_wkbks_exception_log.txt
updt_fields_json_fn: metadata_updt_fields.json


#socrata specific configs
row_id_field: row_id
src_records_cnt_field: SrcRecordsCnt
dataset_records_cnt_field: DatasetRecordsCnt
fourXFour: fourXFour
isLoaded: isLoaded
datasets_to_load_fn: datasets_to_load.csv
dataset_name_field: Socrata Dataset Name
dataset_src_dir_field:  Dataset_Source_Dir
dataset_src_fn_field: Dataset Source Filename
base_url: data.sfgov.org
job_name: Update Master Data Dictionary after Workbook Creation


#lists of things

sheet_keys: ["columnid", "dataset_name", "open_data_portal_url", "field_name", "field_type", "field_definition", "field_alias", "field_type_flag"]
steward_keys: ["data_steward", "department", 'data_steward_name']

fieldType_flag: ["Category", "Unique"]

wkbk_formats:
    format1:
        wksht_name: DataDictionary
        skip_rows: 4

valsToNotOverride: ['Complete', "Do Not Process", "Submitted by Coordinator" , "Submitted by Steward"]
