master_data_dictionary:
    #fourXFour: 8zp7-ik63
    fourXFour: asfx-iyhm
    Socrata Dataset Name: Master Data Dictionary
    row_id: columnid
    json_fn: master_data_dictionary.json
field_types:
    fourXFour: 8efc-aram
    json_fn: field_types.json
    columns_to_fetch: field_type
global_fields:
    fourXFour: ctmu-r9d9
    json_fn: global_fields.json
    columns_to_fetch: global_string,field_name
