master_data_dictionary:
    #fourXFour: 8zp7-ik63
    fourXFour: asfx-iyhm
    Socrata Dataset Name: Master Data Dictionary
    row_id: columnid
    json_fn: master_data_dictionary.json
    columns_to_fetch: columnid,datasetid,dataset_name,open_data_portal_url,inventoryid,field_name,field_alias,socrata_field_type,field_type,field_definition,field_type_flag,api_key,data_steward,data_steward_name,department_from_inventory,department_from_catalog,department,data_coordinator,data_dictionary_attached,field_documented,attachment_url,global_field,do_not_process,status,date_last_changed

field_types:
    fourXFour: 8efc-aram
    json_fn: field_types.json
    columns_to_fetch: field_type
global_fields:
    fourXFour: ctmu-r9d9
    json_fn: global_fields.json
    columns_to_fetch: global_string,field_name
