client_key: /home/ubuntu/workspace/configs/your_google_app_key.json
wkbk_key_master: your_google_spreadsheet_wkbk_key

config_dir: /home/ubuntu/workspace/configs/
email_config_file: email_config.yaml


pickle_dir: /home/ubuntu/workspace/pickled/

wkbk_output_dir: /home/ubuntu/workspace/output_wkbks/
wkbk_output_json: workbooks_info.json


datadict:
    sht_name: VIEW_master_fields
    pickle_name: data_dict

stewards:
     sht_name: import_data_coordinators
     pickle_name: stewards


field_types:
    sht_name: field_types
    pickle_name: field_types

log_dir: /home/ubuntu/workspace/logs/
email_config_fname: email_config.yaml
exception_logfile: exception_log.txt


update_info:
    wkbk_key: your_google_spreadsheet_wkbk_key
    updt_sht_name: field_definitions
    field_positions:
        columnID: A
        field_alias: E
        field_definition: F
        field_type_flag: G
        status: H
        date_last_changed: J
    field_name_mappings:
        columnID: columnID
        field_alias: Field Alias
        field_definition: Field Definition
        field_type_flag: Field Type Flag

    statuses:
        for_review_steward: For Review by Steward
        submitted_steward: Submitted by Steward
        complete: complete


sheet_keys: ["columnID", "Dataset Name", "Open Data Portal URL", "Field Name", "Field Type", "Field Definition", "Field Alias", "Field Type Flag"]
steward_keys: ["Email", "Department", "First Name", "Last Name", "Dept Code"]
screendoor_config_file: screendoor_configs.yaml


updt_fields_json_fn: metadata_fields.json
wkbk_uploads_dir: /home/ubuntu/workspace/wkbk_uploads/

documented_fields_dir: /home/ubuntu/workspace/documented_fields
